# -*- coding: utf-8 -*-
"""dim_calendar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gzt-ZJsAUDQZPzlkN-zAIwwwNmobn1gu
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Define the date range (modify as needed)
start_date = "2020-01-01"
end_date = "2030-12-31"

# Create a date range
date_range = pd.date_range(start=start_date, end=end_date, freq='D')

# Function to determine if a date is a holiday (basic version)
# You can replace this with actual holiday data for your region
def is_holiday(date):
    # Example: Marking only weekends as holidays (modify with actual holiday list)
    return 1 if date.weekday() in [5, 6] else 0  # Saturday & Sunday

# Create the dim_calendar DataFrame
dim_calendar = pd.DataFrame({
    "date_key": date_range,
    "day_of_week": date_range.strftime("%A"),  # Full day name
    "month": date_range.strftime("%B"),        # Full month name
    "year": date_range.year,
    "quarter": date_range.to_series().dt.to_period("Q").astype(str),  # Q1, Q2, etc.
    "is_holiday": [is_holiday(date) for date in date_range]  # Assign holidays
})

# Display the first few rows
print(dim_calendar.head())

# Save to CSV (Optional)
dim_calendar.to_csv("dim_calendar.csv", index=False)

